#!/bin/bash
###
# Runs shellcheck on .sh files in repo
###

anyerr=0

tmpdir=/tmp/gittmp/$(basename $(git base-dir))
mkdir -p $tmpdir

git ls-files > $tmpdir/files

errfiles=""
for modified in $(git diff --staged --name-only "*.sh"); do
    tmpfile=$tmpdir/$(basename $modified)
    git show :$modified > $tmpfile

    baseno=$(dirname $modified)/.$(basename $modified)
    if [[ ! -e ${baseno}.noshellcheck ]]; then
        if ! shellcheck $tmpfile; then
            errfiles+="$modified (shellcheck)"
        fi
    fi
done

if [[ $errfiles != "" ]]; then
    echo "Encountered shellcheck errors..."
    echo $errfiles
    sleep 5
fi

exit 0
